### ISSUE TITLE
Files for the SaaC data

### ISSUE THREAD

**Issue by Guzpenha** [PengjieRen/CaSE-1.0#2]
Hi, I cannot find the conversations from the SaaC dataset. How can I download it?

**Comment by PengjieRen** [comment]
Hi, please find the reformulated queries of CAsT in 'dataset/cast/cast.reformulation.query' and the summarized answers in 'dataset/cast/cast.answer'. For the other CAsT data, I sugguest downloading from their website, because I am not sure I am allowed to distribute it here.
